#!/bin/bash

pkgs="python
nethogs
libssl-dev
cifs-utils
python-psutil"
#mysql-server"


apt update
#debconf-set-selections <<< 'mysql-server mysql-server/root_password password root'
#debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password root'
apt -y install $pkgs
