heat_template_version: 2016-04-08
description: Ubuntu 16.04_64 Application server.

parameters:
  key_name:
    type: string
    description: Name of Appserver SSH Key.
  subnet:
    type: string
    description: Name of Appserver Network.
  member_pool_id:
    type: string
    description: Pool ID that the server will be attached to be member of a loadbalancer.
  server_group:
    type: string
    description: Autoscalling server_group
  db_host:
    type: string
  db_name:
    type: string
  db_user:
    type: string
  db_pass:
    type: string
  image_name:
    type: string
  flavor_name:
    type: string
  security_group:
    type: string
  network_name:
    type: string
  shared_fpath:
    type: string

resources:
  server:
    type: OS::Nova::Server
    properties:
      name: appserver
      image: {get_param: image_name}
      flavor: {get_param: flavor_name}
      key_name: {get_param: key_name}
      metadata: {"metering.server_group": {get_param: server_group}}
      user_data_format: RAW
      user_data:
        str_replace:
          template: {get_file: config_scripts/appserver.sh}
          params:
            $db_host: {get_param: db_host}
            $db_name: {get_param: db_name}
            $db_user: {get_param: db_user}
            $db_pass: {get_param: db_pass}
            $shared_fpath: {get_param: shared_fpath}
      networks:
        - subnet: {get_param: subnet}
      security_groups: [{get_param: security_group},default]

  lb_member:
    type: OS::Neutron::LBaaS::PoolMember
    properties:
      address: {get_attr: [server, networks, {get_param: network_name}, 0]}
      admin_state_up: True
      pool: {get_param: member_pool_id}
      protocol_port: 9000
      subnet: {get_param: subnet}
